#!/bin/bash
# =============================================================================
# generate-target.sh
#
# Generates rcp.target with absolute paths for CLI Tycho builds on Windows.
# Run this BEFORE mvn clean install on any Modelio module.
#
# Usage:
#   export ECLIPSE_WS="C:/Users/you/source/repos/Modelio"
#   ./generate-target.sh
# =============================================================================

set -e

ECLIPSE_WS="${ECLIPSE_WS:-$(cd "$(dirname "$0")" && pwd -W 2>/dev/null || pwd)}"
TARGET_FILE="$(dirname "$0")/dev-platform/rcp-target/rcp.target"
BASE="$ECLIPSE_WS/dev-platform/rcp-target"
RES="$ECLIPSE_WS/dev-platform/pack-resources"

echo "Generating rcp.target with ECLIPSE_WS=$ECLIPSE_WS"

cat > "$TARGET_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<!-- AUTO-GENERATED by generate-target.sh — do not edit manually -->
<target includeMode="slicer" name="rcp" sequenceNumber="30">
	<locations>
		<location path="$BASE/javax/jaxb" type="Directory"/>
		<location path="$BASE/rcp-eclipse/eclipse" type="Directory"/>
		<location path="$BASE/rcp-eclipse/eclipse-fr" type="Directory"/>
		<location path="$BASE/rcp-eclipse/swt" type="Directory"/>
		<location path="$BASE/modelio-integ/org.astyle/astyle" type="Directory"/>
		<location path="$BASE/modelio-integ/apache/tika" type="Directory"/>
		<location path="$BASE/modelio-integ/apache/jena" type="Directory"/>
		<location path="$BASE/modelio-integ/apache/xerces" type="Directory"/>
		<location path="$BASE/modelio-integ/oauth/oauth" type="Directory"/>
		<location path="$BASE/modelio-integ/sf-practicalxml/praticalxml" type="Directory"/>
		<location path="$BASE/modelio-integ/org.jdbm/jdbm" type="Directory"/>
		<location path="$BASE/apache/log4j" type="Directory"/>
		<location path="$BASE/apache/commons-compress" type="Directory"/>
		<location path="$BASE/apache/commons-lang" type="Directory"/>
		<location path="$BASE/apache/freemarker" type="Directory"/>
		<location path="$BASE/org.eclipse/nebula-nattable" type="Directory"/>
		<location path="$BASE/org.eclipse/nebula-incubator" type="Directory"/>
		<location path="$BASE/org.eclipse/nebula" type="Directory"/>
		<location path="$BASE/org.eclipse/gef-draw2d" type="Directory"/>
		<location path="$BASE/org.eclipse/uml2" type="Directory"/>
		<location path="$BASE/org.eclipse/emf" type="Directory"/>
		<location path="$BASE/tmatesoft/svnkit-1.10.9" type="Directory"/>
		<location path="$BASE/org.slf4j/slf4j" type="Directory"/>
		<location path="$BASE/ch.qos/logback" type="Directory"/>
		<location path="$RES/openjdk-jre11" type="Directory"/>
	</locations>
</target>
EOF

echo "Generated: $TARGET_FILE"
